version: '3.8'
# # postgres
# services:
#   dev-db:
#     image: postgres:13
#     ports:
#       - 5434:5432
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 123
#       POSTGRES_DB: nest
#     networks:
#       - fawinell
#   test-db:
#     image: postgres:13
#     ports:
#       - 5435:5432
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 123
#       POSTGRES_DB: nest
#     networks:
#       - fawinell
# networks:
#   fawinell:

# mysql
services:
  dev-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'dev-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:

